/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DESAFIO1;

import javax.swing.JOptionPane;

/**
 *
 * @author domin
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    private int r;
    private final Prato massa = new Prato("Lasanha", "");
    private final Prato massa_n = new Prato("Bolo de Chocolate", "");

    private final PratosL prato_massa = new PratosL();
    private final PratosL prato_massa_n = new PratosL();

    public Game() {
        initComponents();
        this.prato_massa.getPratos().add(massa);
        this.prato_massa_n.getPratos().add(massa_n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jogo Gourmet");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pense em prato que goste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        start();
        this.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

//comecar o jogo
    private void start() {
        r = JOptionPane.showConfirmDialog(rootPane, "O prato que você pensou é massa ?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (r == JOptionPane.YES_OPTION) {
            guess(prato_massa);
            return;
        }

        guess(prato_massa_n);
    }

    //Adivinhar o prato que a pessoa pensou
    private void guess(PratosL pratos) {
        int cont;
        int sizeList = pratos.getPratos().size() - 1;

        //percorrer a arraylist
        for (cont = sizeList; cont > 0; cont--) {
            r = ask_for_dish(pratos, cont, true);

            if (r == JOptionPane.YES_OPTION) {

                r = ask_for_dish(pratos, cont, false);

                if (r == JOptionPane.YES_OPTION) {

                    win();
                    break;
                } else if ((r == JOptionPane.NO_OPTION) && (cont == 0)) {

                    addDish(pratos, cont);
                    break;
                }
            }
        }

        if (cont == 0) {

            r = ask_for_dish(pratos, cont, false);

            if (r == JOptionPane.YES_OPTION) {

                win();
                return;

            }

            addDish(pratos, cont);
        }
    }

    // adicionar os pratos na lista
    private void addDish(PratosL pratos, int ordemPrato) {
        pratos.getPratos().add(newObjt(pratos, ordemPrato));
    }

    //win message
    private void win() {
        JOptionPane.showMessageDialog(rootPane, "Acertei de novo!", "Acertei", JOptionPane.INFORMATION_MESSAGE);
    }

    // perguntar sobre os pratos
    private int ask_for_dish(PratosL pratos, int cont, boolean caract) {
        if (caract) {
            return JOptionPane.showConfirmDialog(rootPane, "O prato que pensou é " + (pratos.getPratos().get(cont).getPrato_caract()) + (" ?"), "Confirma", JOptionPane.YES_NO_OPTION);
        }

        return JOptionPane.showConfirmDialog(rootPane, "O prato que pensou é " + (pratos.getPratos().get(cont).getPrato_desc()) + (" ?"), "Confirma", JOptionPane.YES_NO_OPTION);
    }

    //criar novo o objeto de prato 
    private Prato newObjt(PratosL pratos, int ordemPrato) {
        String descricaoPrato = JOptionPane.showInputDialog(rootPane, "Qual prato você pensou ?", "Desisto", JOptionPane.QUESTION_MESSAGE);
        String caracteristicaPrato = JOptionPane.showInputDialog(rootPane, descricaoPrato + (" é ________ mas ") + (pratos.getPratos().get(ordemPrato).getPrato_desc()) + (" não."), "Complete", JOptionPane.QUESTION_MESSAGE);

        Prato prato = new Prato(descricaoPrato, caracteristicaPrato);

        return prato;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
